msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-10-26 17:01+0000\n"
"Last-Translator: \n"
"Language-Team: Korean\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: ko\n"
"X-Crowdin-File-ID: 670\n"
"Language: ko_KR\n"

#: redbot/cogs/audio/core/events/dpy.py:40
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "I'm missing permissions in this server, Please address this as soon as possible.\\n\\nExpected Permissions:\\n"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Enabled"
msgstr "활성화됨"

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Disabled"
msgstr "비활성화됨"

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "No DJ role found. Disabling DJ mode."
msgstr "DJ역할을 찾지 못했습니다. DJ역할을 비활성화합니다."

#: redbot/cogs/audio/core/events/dpy.py:134
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:142
msgid "Unable To Parse Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:154
#: redbot/cogs/audio/core/events/dpy.py:163
msgid "Invalid Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:155
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:175
msgid "Invalid Environment"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:176
msgid "Connection to Lavalink has been lost."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:184
msgid "No Player Available"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:185
msgid "The bot is not connected to a voice channel."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:193
#: redbot/cogs/audio/core/events/lavalink.py:98
msgid "Unable to Get Track"
msgstr "트랙을 찾을수 없습니다"

#: redbot/cogs/audio/core/events/dpy.py:194
#: redbot/cogs/audio/core/events/lavalink.py:99
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:205
msgid "There was an issue communicating with Discord."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:206
msgid "This error has been reported to the bot owner."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:89
msgid "Couldn't get a valid track."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:121
msgid "Auto Play started."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:136
msgid "Now Playing"
msgstr "지금 재생 중"

#: redbot/cogs/audio/core/events/lavalink.py:138
msgid "Track length: {length} | Requested by: {user}"
msgstr "곡 길이: {length} | 신청자: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:159
msgid "Queue ended."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:202
msgid "Multiple Errors Detected"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:203
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "오디오 플레이어를 오류로 중지합니다. 오디오 명령어가 작동되지 않을수 있습니다."

#: redbot/cogs/audio/core/events/lavalink.py:217
msgid "Track Stuck"
msgstr "트랙 걸림"

#: redbot/cogs/audio/core/events/lavalink.py:218
msgid "Playback of the song has stopped due to an unexcepted error.\\n{error}"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:224
msgid "Track Error"
msgstr "트랙 에러"

